[build-system]
requires = ["setuptools",
            "setuptools_scm>=6.2",
            "cython>=3.0.0, <4",
            "numpy>=2.0.0, <3",
            "extension-helpers>=1,<2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pyregion/version.py"
