{% set name = "pyregion" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('PYREGION_VERSION', version) }}

source:
  git_url: https://github.com/jasercion/pyregion.git

requirements:
  build:
    - cython
    - numpy >=2.*
    
  host:
    - cython
    - numpy >=2.*
    
  run:
    - cython
    - numpy >=2.*

about:
  home: https://github.com/jasercion/pyregion
