{% set name = "pyregion" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ environ.get('PYREGION_VERSION', version) }}

source:
  git_url: https://github.com/jasercion/pyregion.git

requirements:
  build:
    - cython
    - numpy
    
  host:
    - cython
    - numpy
    
  run:
    - cython
    - numpy

about:
  home: https://github.com/jasercion/pyregion
