name: CI

on:
  schedule:
    # run every day at 4am UTC
    - cron: '0 4 * * *'
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@924441154cf3053034c6513d5e06c69d262fb9a6  # v1.13.0
    with:
      envs: |
        - macos: py310-test-oldestdeps
        - macos: py311-test
        - macos: py312-test
        - linux: py310-test-oldestdeps
        - linux: py311-test
        - linux: py312-test
      coverage: 'codecov'

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@8c0fde6f7e926df6ed7057255d29afa9c1ad5320  # v1.16.0
    with:
      test_extras: test
      test_command: pytest -p no:warnings --pyargs pyregion
      targets: |
        - cp*-manylinux_x86_64
        - cp*-macosx_x86_64
        - cp*-macosx_arm64
        #- cp*-manylinux_aarch64      
      upload_to_anaconda: true
      upload_to_pypi: false
      anaconda_user: 'jasercion'
    secrets:
      anaconda_token: ${{ secrets.ANACONDA_TOKEN }}
  
  conda_deployment:
    name: Conda deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.11
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v2.0.0
        with:
          meta_yaml_dir: conda/meta.yaml # Replace with the path to your meta.yaml directory
          user: jasercion # Replace with your Anaconda username (or an Anaconda organization username)
          token: ${{ secrets.ANACONDA_TOKEN }} # Replace with the name of your Anaconda Token secret
